### PR TITLE
Fix repo url; update version; explain builder which files to build

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by tbowmo** [comment]
you are targeting development branch, where we still have the -beta added to the version string.

(We do not accept PR's against master)

**Comment by ivankravets** [comment]
Could update this manifest without PR? Thanks.

**Comment by tbowmo** [comment]
We are preparing a bugfix release within the next couple of weeks,where this could come in to master.

Could you change your commit so that it still have - beta added to the version string? Then we can accept it

**Comment by ivankravets** [comment]
Thanks, done!

**Pull request merged**
