### PR TITLE
ShiftPresentation

### PR DESCRIPTION
**Pull request by dmacias72**
Previous Jul, 17 commit (934ccf30b205afad2086c908a367c4205ce580cd) moved setup after presentation. Noticed dallas temp sensors not working anymore after this commit. Moved presentation after setup.

### CODE REVIEW

**Comment by henrikekblad** [comment]
You can implement the before method in your sketch

```
void before()  {
   // Initialise things before the MySensors library
}
```

**Comment by dmacias72** [comment]
I moved the sensors.begin(); to void before{} and all works fine now with current dev branch. However was the previous Jul, 17 correct. in order to Call _nodeRegistration() before setup(), setup() was moved after presentNode(); If thats correct then the DallasTemperatureSensor sketch should be corrected with void before{sensors.begin();} I hope that makes sense.  But basically with the current dev branch the DallasTemperatureSensor sketch doesn't present a temp sensor.

**Comment by henrikekblad** [comment]
Ok, good find. 

Could you create the pull request against DallasSensor in MySensorsArduinoExamples repo? 

BTW, which version of the Arduino IDE are you running? There seem to be some weird problems in 1.6.10 we're currently investigating.

**Comment by dmacias72** [comment]
I can create a PR for the dallas temp sketch. I'm using Arduino IDE 1.6.9.  The only other thing I noticed was the MYSBootloader OTA 1.3 pre serial upload through the IDE is broken sometime after MySensors 2.0 release.  I haven't had time to track that down yet. Not sure if it's on tekka's end, MySensors or IDE.

**Comment by tekka007** [comment]
Arduino 1.6.10 includes a newer avrdude version (6.3) - several posts indicate upload issues with this avrdude release.

**Pull request closed without merging**
