### PR TITLE
Cleanup debug messages in MySensorsCore

### PR DESCRIPTION
**Pull request by tekka007**
Introducing transparent debug log format **SYSTEM[:SUB SYSTEM]:MESSAGE** for easier troubleshooting.

Example: `MCO:REG:REQ`

system: `MCO `refers to `MySensorsCore`
sub system: `REG `refers to `_registerNode()`
message: `REQ` = registration request

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tbowmo** [comment]
Do you have a complete list of the abbreviations that is used for the
different subsystems?

Den tor. 28. jul. 2016 00.06 skrev Olivier <notifications@github.com>:

**Comment by tekka007** [comment]
@tbowmo yes, you'll find that information in the MySensors Architecture doc

**Comment by fallberg** [comment]
I'd also propose such a list is added to doxygen (if it isn't already)

**Comment by tbowmo** [comment]
What he said ^^^^ :)

Den lør. 30. jul. 2016 19.12 skrev Patrick Fallberg <
notifications@github.com>:

**Comment by tekka007** [comment]
Jenkins, build examples please

**Pull request merged**
