### PR TITLE
RFM69 frequency band for India - 865MHz

### LINKED ISSUE #1184: RFM69 Frequency support for India band (865 to 867 MHz)
In India, 868 Mhz is a licensed band. 
License-free band 865 to 867 MHz.
RFM69 868 module can support for this range (supports 862 to 890 MHz, Page 12 in the datasheet)

image

So adding `RFM69_865MHZ` option in frequency selection list will be good for me :)
Center frequency can be 866 MHz.

### PR DESCRIPTION
**Pull request by jkandasa**
Fixes #1184

### CODE REVIEW

**Comment by tekka007** [comment]
@jkandasa Why not taking the center frequency as identifier, i.e. RFM69_866MHZ?

**Comment by jkandasa** [comment]
@tekka007 widely they call this band 865MHz(865~867MHz), but it is a starting frequency.
What is the bandwidth range for RFM69 from the center frequency(both side)?

**Comment by jkandasa** [comment]
@tekka007 if total bandwidth is less than 500KHz I can go with 865xxx000 frequency. I do not have any idea about RFM69 Maximum bandwidth.
Can you guide me?

**Comment by tekka007** [comment]
@jkandasa According to http://www.hoperf.com/upload/rf/RFM69HW-V1.3.pdf Table 14 the maximum bandwith is 500kHz. The default MySensors RFM69 settings is 125kHz: https://github.com/mysensors/MySensors/blob/development/drivers/RFM69/new/RFM69_new.h#L211

**Comment by jkandasa** [comment]
@tekka007 Thank you! Now I have switched center frequency to 865.5 MHz.

**Pull request merged**
