### PR TITLE
Fix SPIDEV interrupt and GPIO double export

### LINKED ISSUE #1208: SPIDEV interupt broken
RF24 Setup [here](https://github.com/mysensors/MySensors/blob/development/drivers/RF24/RF24.cpp#L513) exports the pin,
and then `attachInterrupt` [here](https://github.com/mysensors/MySensors/blob/development/drivers/RF24/RF24.cpp#L528) does it again inside [here](https://github.com/mysensors/MySensors/blob/development/drivers/Linux/interrupt.cpp#L145-L163) 

AFAIK the `interrupt` code can just be removed. I tested out on BBB and it worked alright.

### LINKED ISSUE #1209: not getting packets with SPIDEV uart or ethernet
my `configure` command looks like: 
```
./configure --c_compiler=/home/connor/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.1.0/bin/arm-unknown-linux-gnueabihf-gcc --cxx_compiler=/home/connor/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.1.0/bin/arm-unknown-linux-gnueabihf-g++ --my-gateway=serial --my-transport=rf24 --my-config-file=/tmp/mysensors.conf --my-debug=enable --my-serial-port=/dev/ttyMySGW --my-serial-baudrate=115200 --my-serial-is-pty --my-signing=none --bin-dir=/home/connor/oss/elixir/my_sensors/my_sensors_mysgw/priv/my_sensors --build-dir=/home/connor/oss/elixir/my_sensors/my_sensors_mysgw/_build/my_sensors --prefix=/home/connor/oss/elixir/my_sensors/my_sensors_mysgw/priv/my_sensors --cpu-flags="-march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard" --extra-cxxflags="-std=c++98" --soc="AM33XX" --spi-driver="SPIDEV" --my-rf24-irq-pin="47" --spi-spidev-device=/dev/spidev1.0
```

I get plenty of logs for example: 
```
00:10:43.096 [info] TSF:MSG:READ,7-7-255,s=255,c=3,t=7,pt=0,l=0,sg=0:
00:10:43.096 [info] Jan 01 00:10:43 DEBUG TSF:MSG:BC
00:10:43.096 [info] Jan 01 00:10:43 DEBUG TSF:MSG:FPAR REQ,ID=7
00:10:43.096 [info] Jan 01 00:10:43 DEBUG TSF:PNG:SEND,TO=0
00:10:43.096 [info] Jan 01 00:10:43 DEBUG TSF:CKU:OK
00:10:43.097 [info] Jan 01 00:10:43 DEBUG TSF:MSG:GWL OK
00:11:00.016 [info] Jan 01 00:11:00 DEBUG
```

But those messages never go to `/dev/ttyMySGW`. I get the same results on `ethernet`

### PR DESCRIPTION
**Pull request by ConnorRigby**
Let me know if i should remove the debug logs.
Fixes #1208

### CODE REVIEW

**Comment by mfalkvidd** [comment]
I'm not familiar with how the gpio interfece works, but could you explain why
sys/class/gpio/export and
sys/class/gpio/gpio%d/direction
causes double export while sys/class/gpio/gpio%d/edge does not?

**Comment by mfalkvidd** [comment]
@ConnorRigby have you had any chance to look at my question?

**Comment by ConnorRigby** [comment]
@mfalkvidd very sorry i was not receiving notifications for this issue. It's been so long since i put this together, that i can't actually remember much of the details of it but basically the current system 
_works_ on `BRCM` drivers, but _does not_ work on `SPIDEV` drivers.

This patch fixed `SPIDEV`, but i think actually broke `BRCM` drivers. I didn't investigate much further because i switched to rfm69 based radios which doesn't seem to have this problem.

**Comment by mfalkvidd** [comment]
Thanks for your reply @ConnorRigby 
Does this mean we should close this pull request? Breaking BRCM doesn't sound like a good idea.

**Comment by mfalkvidd** [comment]
Closing for now. Feel free to reopen.

**Pull request closed without merging**
