### PR TITLE
Update configure

### PR DESCRIPTION
**Pull request by LouiS22**

### CODE REVIEW

**Comment by marceloaqno** [comment]
For which model or version of RPi is this fix required?
Could you give more information?

**Comment by LouiS22** [comment]
Oh, sorry, forgot to include it. I have a Raspberry Pi 2 Model B 1GB.

**Comment by marceloaqno** [comment]
Could you provide the /proc/cpuinfo?

**Comment by LouiS22** [comment]
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2835
Revision        : a01041
Serial          : 00000000f3e660e6

**Comment by marceloaqno** [comment]
Thanks for the info, this may give more information to the subject:
https://github.com/raspberrypi/firmware/issues/705

**Comment by marceloaqno** [comment]
I've added your changes to #827 with some improvements

**Pull request closed without merging**
