### PR TITLE
Refactor signing backend

### PR DESCRIPTION
**Pull request by fallberg**
Removed some cppcheck isues in the process.

### CODE REVIEW

**Comment by fallberg** [comment]
Jenkins, build

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
@bblacey I believe they are the result of sublime text autostyling of files outside the core.

**Comment by fallberg** [comment]
@bblacey sorry, no, actually it was the sublime text project being out of sync, corrected now

**Comment by bblacey** [comment]
I suspected as much, maybe SublimeText can use the AStyle bundle ;)  At a minimum, the pre-commit hook should have caught the difference between SublimeText and the bundle.  Have you run bootstrap-dev on your repo?  I would  have thought you would be the first out of the gate :)

**Comment by fallberg** [comment]
I have not yet, as my upstream is configured differently than the bundle require and I have not yet bothered to reset. Sublime cannot use the bundle for its plugins unless you want to develop new plugins ;)

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
@tekka007 Thanks, good catch. I think I will make a tester for signing on gateways

**Comment by fallberg** [comment]
Gitler2G, check this please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by bblacey** [comment]
Gitler2G, check this please

**Comment by bblacey** [comment]
Gitler2G, check this please

**Comment by sbrinkmann** [comment]
I just spend some hours testing the just released MySensors version with the refactored signing backend. I use an ESP8266 with soft signing, which now works with the fix #696 which uses the integrated random number generator. On my others nodes I use the ATSH204. So far I haven't seen any flaws. Hope this applies also to the long term usage 😎 Good job!

**Pull request merged**
