### PR TITLE
Update GatewayW5100MQTTClient.ino w instructions

### PR DESCRIPTION
**Pull request by sundberg84**
I think this file has the incorrect information (ESP8266 instructions) so i removed them and added what i think is correct. 

I agree to CLA.

### CODE REVIEW

**Comment by sundberg84** [comment]
I dont know why its saying Git commit message not good enough. Anyone?

**Comment by fallberg** [comment]
" I have mailed the details to the PR author." Did you not get the mail?

**Comment by henrikekblad** [comment]
An email with instructions should have been sent to you by the build server. I suspect the first line of the commit message was too long. You should keep it under 50 chars. The reason is to make the gitlog readable.

Do like this:
https://help.github.com/articles/changing-a-commit-message/

**Comment by sundberg84** [comment]
@fallberg @henrikekblad Tnx guys! I did, but i got in my spam and I didnt check. Sorry!
New to github but learning, want to be able to contribute when i find something. Ill change the commit message!

**Comment by fallberg** [comment]
Just remember that commit message and pull request title are two different things :)

**Comment by sundberg84** [comment]
Nope, that didnt work... is it the description "I think this file has the incorrect information (ESP..." thats wrong? Sorry for messing it up here... ill just close it if it gets to messy.

**Comment by fallberg** [comment]
The mail you got should give you exact instructions on how to amend your commit in a shell.
Remember that the commit headline needs to be separated from the "body" using a blank line.

**Comment by fallberg** [comment]
What you have now is two commits. You should have committed using --amend and force pushed the result. Alternatively used interactive rebase. It's all in the mail.

**Comment by sundberg84** [comment]
@fallberg Sorry, I have the desktop version... and made something wrong.
Ill close this and maybe you can make the changes in one of your push later on. 
Ill read some more and see if i can figure it out next time.

**Comment by fallberg** [comment]
@sundberg84 you can open a shell through the app. Just click the gear icon. Git cannot exist without a shell so you have it although the github app tries its best to hide it from you. Unfortunately.

**Pull request closed without merging**
