### PR TITLE
Linux: Support keys in config file

### PR DESCRIPTION
**Pull request by marceloaqno**
- Signing (HMAC, serial) and encryption keys are set through the configuration file.
- SoftEeprom update.

### CODE REVIEW

**Comment by fallberg** [comment]
This probably require the rPi specifics in MySigning.h doxygen block to be updated.

**Comment by mfalkvidd** [comment]
Adding release-notes label since this change alters how personalization is done. instructions on mysensors.org will need to be updated.

**Comment by fallberg** [comment]
I agree on the release notes but the homepage should not contain personalisation specifics. It should link to doxygen which will update automatically.

**Comment by mfalkvidd** [comment]
You're right about the homepage. I confused these changes with https://github.com/mysensors/MySensors/pull/1061

**Comment by fallberg** [comment]
Good idea with the label. Helps tracking those sneaky ones we might forget to mention on release day. Should reduce some forum chatter, or at least focus it a bit.

**Pull request merged**
