### PR TITLE
nRF51/nRF52 platform

### PR DESCRIPTION
**Pull request by d00616**
This is the support of the Nordic Semiconductor NRF51 (nrf51822, nrf51422) and NRF52 (nrf52832) platform. The nRF5 MCU provides a one chip solution for MySensors for very small devices. The MCU is flexible with a lot of integrated peripherals and flexible assignment of output pins.

Requires arduino-nRF5 (https://github.com/sandeepmistry/arduino-nRF5).

The Radio is working in an NRF24 compatible mode (ESB). BLE is not supported. The SoftDevice needs to be removed by a "mass erase" operation or my erase all example script: https://github.com/d00616/arduino-NVM/tree/master/examples/flash_erase_all

Currently, when the sleep mode is used the MCU sleeps with a current of ~3uA when the timer is enabled. When Pin wake up is configured the MCU sleeps with a current of 1mA. This needs fixing at Arduino level.

The included "NVM" driver allows an EEPROM like access to the last 16k/32k of Flash pages.  The available write cycles per cell are equal or better than real EEPROM's, but when the log is full a write process can stop for 4 seconds. I have added a logic into hwSleep to empty the log when less than 32 write operations are available. The NVM library can easily ported to ESP8266 or SAMD by providing a Flash interface.

Like SAMD, the nRF5 MCU supports low current and high current output modes. These modes are not supported by Arduino. I have added some enhanced output modes like OUTPUT_S0S1 ... OUTPUT_H0D1 into hwPinMode.

Configuring an pull up resistor with 	pinMode(..., INPUT) followed by digitalWrite(..., HIGH) doesn't work. It has to replaced by hwPinMode(..., INPUT_PULLUP) or pinMode(..., INPUT_PULLUP).

### CODE REVIEW

**Comment by tekka007** [comment]
@d00616 Your PR needs some attention - please let us know if you need help in solving the Jenkins issues.

**Comment by d00616** [comment]
@tekka007 Thank you. Jenkins reports a lot of style warnings on files I have not modified.

Next warnings are about missing documentation, I provide later.

At the moment I working on sleep modes, then I will check the Radio protocol. It's possible there is a timing issue when Debug messages are disabled. When this is finished I will add the Doxygen documentation missed by Jenkins.

When the documentation is finished, I think the code is ready to merge.

**Comment by tekka007** [comment]
@d00616 ok, sounds good :)

**Comment by d00616** [comment]
My commits are not shown correctly. I create a new Pull Request shortly.

**Pull request closed without merging**
