### PR TITLE
Add log parser

### PR DESCRIPTION
**Pull request by mfalkvidd**
Add the log parser to git so we have version control/history, can create issues and can receive pull requests.

### CODE REVIEW

**Comment by tekka007** [comment]
Can this file be loaded from the log parser page?

**Comment by mfalkvidd** [comment]
No. Github prevents loading javascript remotely, by setting text/plain as content type.
There are some workarounds, but they all seem to be cludgy.
https://stackoverflow.com/a/19285701

**Comment by mfalkvidd** [comment]
But maybe Jenkins kan push the file to mysensors.org, just like it does with doxygen?

**Comment by henrikekblad** [comment]
I already do some magic parsing of the articles to handle the inclusion (and caching) of code from github. Might be possible to adopt it to allow inclusion of the logparser code.

**Comment by mfalkvidd** [comment]
Don't merge yet. Hek proposed some changes through slack.

**Comment by mfalkvidd** [comment]
Ready for merge. Can now be run offline by opening logparser.html in a web browser.

**Pull request merged**
