### PR TITLE
HAL for digitalRead/Write() and pinMode()

### PR DESCRIPTION
**Pull request by tekka007**
- Pin IO abstraction for all architectures
- use digitalWriteFast(), digitalReadFast() & pinModeFast() for AVR: speeding up pin access & reduce flash

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by cimba007** [comment]
Just a note. digitalReadFast will return 0 if the pin is low and will return **NON-ZERO** if it is high. This could be anything .. but doesn't have to be 1. Additional care might be neccessary if comparing the result of digitalReadFast like here:

> if (!_inclusionMode && hwDigitalRead(MY_INCLUSION_MODE_BUTTON_PIN) == MY_INCLUSION_BUTTON_PRESSED)

Was just a hint ;-) Did not take my time to do a full test.

**Comment by tekka007** [comment]
@cimba007 digitalReadFast() uses bitRead() returning 0 or 1 (see implementations)

**Comment by cimba007** [comment]
My bad .. it seems I used an early draft version of digitalWriteFast-Library from the Arduino forums which defined bitRead as an macro with incorrect shifting. Everything is ok now ;-)

**Comment by tekka007** [comment]
- This PR + #561 is a fix for #578

**Comment by tekka007** [comment]
Jenkins, build examples please

**Pull request merged**
