### PR TITLE
RFM69 update

### PR DESCRIPTION
**Pull request by tekka007**
WIP - do not merge yet

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by marceloaqno** [comment]
Jenkins, build this please.

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
A rebase probably resolves the Gitler complaints.

**Comment by tekka007** [comment]
PR obsolete, new RFM69 update PR in preparation

**Pull request closed without merging**
