### PR TITLE
Add initial support for use of STM32F1 based boards

### PR DESCRIPTION
**Pull request by PhracturedBlue**
This pull request adds initial support for STM32F1 based Arduino boards. It has been tested with the Maple Mini (using STM32Duino) but should work with others.

These boards can be purchased cheaply, have USB and are 3.3V, and make a good basis for developing sensors.

This request also modifies the RFM69 driver to allow changing the SPI clock frequency, since the STM32F1 boards run at 72MHz, and need a larger SPI_CLOCK_DIV value.

This code has been tested with an RFM69HW, and can communicate with a Arduino Mini Pro gateway

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by tekka007** [comment]
@PhracturedBlue Is this PR still active - if yes, please fix the doxygen warnings as stated [here](http://ci.mysensors.org/job/Verifiers/job/MySensorsArduinoLibPR/865/warnings14Result).

**Comment by PhracturedBlue** [comment]
I do not understand the output of the doxygen report. 
I am looking at this report:
https://ci.mysensors.org/job/Verifiers/job/MySensorsArduinoLibPR/865/cppcheckResult/

 it indicates errors were reduced by 2, warnings increased by 5 and style increased by 1188.  yet I have no idea how to identify which of these violations are related to my patch.  When I select 'new' it shows hundreds of warnings, most of which are in code not touched by this patch.

If someone can explain how I can identify which violations are related to my patch I'll be glad to fix them

**Comment by PhracturedBlue** [comment]
After looking at it some more, I think the actual problem may be this:
https://ci.mysensors.org/job/Builders/job/ArduinoIDEBuilder/16024/warnings2Result/

I can try to fix these, but it would be easier if I could replicate on my own machine.  Are there instructions for running the same tests on my local machine so I can verify the issue is resolved before pushing my updates?

**Comment by PhracturedBlue** [comment]
I have fixed the compiler warning, but I now see a doxygen warning that does not seem to have anything to do with my pull request:

2e0f6b62        (Marcelo Aquino 2017-01-14 19:50:21 -0300       164)    * @**briefTransfer** a buffer of data without an rx buffer

I believe this should be '@brief Transfer' instead, but I don't think fixing this should be part of my pull request.

**Comment by fallberg** [comment]
I suspect your change has caused that file now to be evaluated as part of the build and therefore it starts to be analyzed. I have hotfixed it directly on development, so if you rebase your PR, it should pass.

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
See #795

**Pull request closed without merging**
