### PR TITLE
Add MY_RF24_CHANNEL_CONFIGURABLE directive

### PR DESCRIPTION
**Pull request by Akubi**
Add MY_RF24_CHANNEL_CONFIGURABLE directive in order to allow user to
configure RF24_Channel in before() function of a sketch

### CODE REVIEW

**Comment by Akubi** [comment]
Hi henrikekblad,
Do you test your proposal ?
It's not working to me. 
In <something new> I use core functions like "loadState" and I need MySensors core to be already included.

**Comment by henrikekblad** [comment]
Sorry, I had added a semicolon in the define wrongly above (fixed). Compiles fine here now. 

You can absolutely use loadState in the before().

**Comment by Akubi** [comment]
Hi henrikekblad,
Again, thank for your comment but, of course I also removed the semicolon.
But still not compile. 
I did simply :

> uint8_t RF24_Channel = 12;
#define MY_RF24_CHANNEL RF24_Channel
void before() {
	RF24_Channel = 10;
}
 #include <MySensors.h>

and I have compile errors. In order to avoid errors I have to set the '#include <MySensors.h>'  before
 the rest but in that case it's not working.

After a lot of tests, I figured out that the compiler can be the problem.
I'm using VisualMicro integrated in VisualStudio 2015 and it's generating errors.

If I use Arduino IDE it compile.

Still have to investigate.

**Comment by Akubi** [comment]
Hi henrikekblad,

Ok using Arduino IDE and with the fallowing sequence it's working.

```
#define MY_RADIO_NRF24                           // Enable and select radio type attached
#define MY_DEFAULT_RF_CHANNEL        76          // Default RF Channel at first initialisation
#define MY_RF_EEPROM                250          // EEPROM Slot of the RF Channel

uint8_t RG24_Channel = MY_DEFAULT_RF_CHANNEL;
#define MY_RF24_CHANNEL RF24_Channel

#include <MySensors.h>

...
<some code>
...


void before() {
  // Change Radio Channel
  if (loadState(MY_RF_EEPROM) == 0xFF)
  {
    saveState(MY_RF_EEPROM, MY_DEFAULT_RF_CHANNEL);
  }
  RF24_Channel = loadState(MY_RF_EEPROM);
}
```

The #include <MySensors.h> must be done first in order to use loadState() in before() function.

This still not working with VisulaMicro but ...

We can probably close the "Pull request" 

Thank

**Comment by Akubi** [comment]
Ok, I spend some time discussing with VisualMicro development team.
The problem is identified. VisualMicro problem.
Arduino and VisualMicro have to create and insert prototypes into the code prior to compile in a hidden folder. Currently VisualMicro inserts the prototypes before the first line of code. 
In this code the first line is prior to the #include MySensors.h which is:

`uint8_t RF24_Channel = MY_DEFAULT_RF_CHANNEL;`

This generate a compile error for the propotype :
```
// prototypes
//
void receive(const MyMessage &message);
//
//
```

MyMessage  is not defined at this point.

As a workarround we can add explicit prototypes for MySensor function receive in the sketch.
In that configuration VisualMicro do not generate the prototype and all is ok.

As example : 

```
#define MY_RADIO_NRF24                     // Enable and select radio type attached
#define MY_DEFAULT_RF_CHANNEL  76          // Default RF Channel at first initialisation

// Replace Constant value by local defined variable
uint8_t RF24_Channel = MY_DEFAULT_RF_CHANNEL;
#define MY_RF24_CHANNEL RF24_Channel

#include <MySensors.h>

// MySensors prototypes in order to avoir VisualMicro compile errors
void receive(const MyMessage &message);
```

**Pull request closed without merging**
