### PR TITLE
Fix code style format in core .cpp files

### PR DESCRIPTION
**Pull request by tbowmo**
using :
indent -nut -bli0 -cdb -sc -bap -bad -npsl -ppi2 *.cpp; sed -i -- 's/const const/const/g' *.cpp

### CODE REVIEW

**Comment by henrikekblad** [comment]
Hmm.. all #ifdef indentation stripped. It makes the code a bit more harder to read imho.

**Comment by tbowmo** [comment]
@henrikekblad Yes, especially in our situation where the ifdefs are used very heavily in all the code files. I could see if I could do something about it with the auto formatter..

(Normally I tend to have #ifdefs at start of the line when I write code, like the output is now.. But then again, I haven't used them as much in any other projects :) )

**Comment by tbowmo** [comment]
taking a more soft approach as a starter, and adding {} to control structures only..

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Pull request merged**
