### PR TITLE
Update MyMessage.cpp

### LINKED ISSUE #1349: Not receiving echo anymore
Recently I have updated my ESP32 MQTT gateway to the latest version. 
Now I don't receive an echo anymore. In the previous version I used this was what was shown on the log:
``` 
(15:23:53.015) 961727733 GWT:IMQ:TOPIC=mygateway1-in/30/4/2/1/3, MSG RECEIVED
(15:23:53.015) 961727740 TSF:MSG:SEND,0-0-40-30,s=4,c=2,t=3,pt=0,l=2,sg=0,ft=0,st=OK:60
(15:23:53.015) 961727789 TSF:MSG:READ,30-40-0,s=4,c=2,t=3,pt=0,l=2,sg=0:60
(15:23:53.015) 961727795 TSF:MSG:ECHO
(15:23:53.015) 961727799 GWT:TPS:TOPIC=mygateway1-out/30/4/2/1/3,MSG SENT
```

With the latest version this is shown in the log:

```
(08:59:34.511) 215543368 GWT:IMQ:TOPIC=mygateway1-in/30/4/2/1/3, MSG RECEIVED
(08:59:34.511) 215543375 TSF:MSG:SEND,0-0-40-30,s=4,c=2,t=3,pt=0,l=1,sg=0,ft=0,st=OK:0
```

I'm sure the network is okay since it used to work just fine, and I receive all other messages also. Also, this started after updating the software.

I've tried it with the GatewayESP32MQTTClient example as well.

I'm using the latest ESP32 platformIO release (1.10.0) and the mysensors development branch.

Any ideas? Did I miss a configuration setting perhaps?

### PR DESCRIPTION
**Pull request by rikki78**
Fixes #1349

### CODE REVIEW

**Comment by tekka007** [comment]
Hi Rik, thanks for your contribution!
In order to pass our CI checks, you have to integrate #1351 into #1352 and resubmit this PR. Please also sign the CLA.

**Comment by rikki78** [comment]
All right. I think it should be okay now.

**Comment by rikki78** [comment]
I have to say I had issues after this update of the gateway. I suspect it is because not all nodes and repeaters were updated. So I have the previous commit in a repeater, this didn't work anymore last night.
Can you estimate if this is somehow explainable?

**Comment by rikki78** [comment]
Is the PR now okay? I deleted the wrong branch I think when merging the two together, and now it points to an unknown repository. Let me know if I have to do it again.

**Comment by tekka007** [comment]
Looks good, merging ok. Thanks!

**Pull request merged**
