### PR TITLE
Replace ESP8266 description by W5100 description

### PR DESCRIPTION
**Pull request by mvdw**
This code contains a description of the connection of the hardware for the wrong module.

### CODE REVIEW

**Comment by mvdw** [comment]
Something is wrong here ... how do I solve this mess?

**Comment by fallberg** [comment]
Well, first of all, change your base back to development. PRs to master is not accepted.
The mail from Jenkins contains the information needed to adjust the commit history.

**Comment by mvdw** [comment]
No, I do not get it.
I did change the base back to development. The problem "PRs to master is not accepted." is now solved.
But why these 17 commits? I only want to propose a change to GatewayW5100MQTTClient.ino.
Why do I see my fork as "mvdw/MySensors forked from ntruchsess/MySensors" and not forked from "mysensors/MySensors"?
If this is taking to much of your valued time, ignore me, I will delete everything, study Github things better first, and then later try again anew.

**Comment by fallberg** [comment]
It's very difficult to explain without knowing exactly how you made your fork, branch and push. I'd suggest you start with a clean repo, place your "head" where you want to make the change, (typically development branch of a fork from the MySensors repo), create a local branch from there, apply your change as a commit (mind the constraints on the commit message), push it to github and create a new pr.

**Comment by mvdw** [comment]
OK, the problem is solved.

**Pull request closed without merging**
