### PR TITLE
ESP32: Support HW

### PR DESCRIPTION
**Pull request by tekka007**
Done:
- Jenkins: ESP32 support implemented
- EEPROM: implemented
- GW test: serial ok, ethernet ok
- MQTT client test: ok

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
A rebase probably resolves the Gitler complaints.

**Comment by knopserl** [comment]
Hi, I'm willing to test the ESP32 + RFM95 enhancments, how to ge downlaod that version/build?

**Comment by knopserl** [comment]
I think I found the repository:
https://github.com/tekka007/MySensors/tree/ESP32HW. I will do some testing with a Heltec LoRa board with an ESP32 and RFM95/SX1276

**Comment by knopserl** [comment]
Today, I have tested the repository from tekka007: https://github.com/tekka007/MySensors/tree/ESP32HW and build a GatewayESP32MQTTClient with a dummy sensor node MockMySensors. For both I used a Heltec ESP32 board with a Lora RFM95 chip. I looks to me as it works perfect. I can connect to my remote MQTT Mosquitto broker and it receives dummy sensor data from the sensor node using 868MHz. See serial monitor log extract.
It would be great if this pull request would make it into the master branch in the next upcomming version.
Excellent work tekka007! I got ESP32 and the Lora RFM95 / SX1276 support. That enables great ESP32 all in one boards.

598 GWT:TPC:IP=10.0.0.34
3602 MCO:BGN:STP
3604 MCO:BGN:INIT OK,TSP=1
3606 GWT:TPC:IP=10.0.0.34
3608 GWT:RMQ:MQTT RECONNECT
3639 GWT:RMQ:MQTT CONNECTED
3641 GWT:TPS:TOPIC=GWO1/0/255/0/0/18,MSG SENT
22668 TSF:MSG:READ,254-254-255,s=255,c=3,t=7,pt=0,l=0,sg=0:
22673 TSF:MSG:BC
22675 TSF:MSG:FPAR REQ,ID=254
22678 TSF:PNG:SEND,TO=0
22680 TSF:CKU:OK
22681 TSF:MSG:GWL OK
22931 TSF:MSG:SEND,0-0-254-254,s=255,c=3,t=8,pt=1,l=1,sg=0,ft=0,st=OK:0
24727 TSF:MSG:READ,254-254-255,s=255,c=3,t=7,pt=0,l=0,sg=0:
24732 TSF:MSG:BC

**Comment by tekka007** [comment]
@knopserl Thanks for the feedback!

**Comment by fallberg** [comment]
@knopserl FYI, this PR is part of the 2.3.0 release which is next in line so it will be part of the next release (date TBD).

**Comment by knopserl** [comment]
@tekka007 Thansk an great to hear. I'm happy now with the project as you have provided both ESP32 + RFM95 support and my ESP32/RFM95 board gateway seem to work.

**Comment by knopserl** [comment]
@tekka007 I have successfull tested the MySensors Gateway, it works great with several ESP32 boards, even with the just finished and available PCB from ranseyer.
However, I wanted to build now sensor nodes based on the low power design ESP32s boards using the NodeManager project within MySensors but it looks like this part is not ESP32 enabled, only ESP8266. 
So now my question is: Should this also been addressed with the new MySensors version (2.3 I guess) or is this extra work which is not yet planned?
I have tried to do the port by myself, but it's not just an easy task as I have experienced a couple of incompatibilities. and compile errors.
I'll still try to get it to work but wanted to know if somebody (like tekka) is also working on the ESP32 sensor nodes such as NodeManager is supposed to provide and has far better experience then I currently have?

**Comment by tekka007** [comment]
@knopserl NodeManager is maintained by @user2684. Please direct your question regarding ESP32 compatibility directly to @user2684 (or create a request on https://github.com/mysensors/NodeManager)

**Comment by knopserl** [comment]
ok, I'll do so. I was assuming, that it's a sub-project of mysensors. Thanks.

**Pull request merged**
