### PR TITLE
	Refactor the Doxygen structure

### PR DESCRIPTION
**Pull request by fallberg**

### CODE REVIEW

**Comment by fallberg** [comment]
There is still an issue with the css. Fonts are not correctly referenced. @hek being the web wizard, do you have a suggestion for how to write the css properly so that the fonts work both locally and hosted online without having to hard code the font paths? I've tried relative references and they work locally but when I look at the generated output on jenkins it seem to fail.

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by henrikekblad** [comment]
Remove MACOSX folder...

**Comment by mfalkvidd** [comment]
Should .eps also be marked as binary in .gitattributes? They contain a lot of non-text junk.

**Comment by fallberg** [comment]
@hek it was taken from your stuff, is it obsolete? I don't know any macosx stuff and never will, I'll happily remove the folder, if it does not break things for those miserable sods who are stuck with it...

**Comment by fallberg** [comment]
@mfalkvidd Yes, I will add it.

**Comment by fallberg** [comment]
Jenkins, build examples please

**Pull request merged**
