### PR TITLE
UDP/TCP client mode for esp8266 repaired

### PR DESCRIPTION
**Pull request by soef**

### CODE REVIEW

**Comment by soef** [comment]
Hello, here are the used defines. There are compiler errors with and without defining MY_USE_UDP.

#define MY_GATEWAY_ESP8266
#define MY_ESP8266_HOSTNAME "xxx"
#define MY_ESP8266_SSID "xxx"
#define MY_ESP8266_PASSWORD "***"

//#define MY_USE_UDP

#define MY_PORT 5003
#define MY_GATEWAY_MAX_CLIENTS 2
#define MY_CONTROLLER_IP_ADDRESS 192, 168, 1, 25

**Comment by soef** [comment]
One more info:
no rf-module is used. 
//#define MY_RADIO_NRF24
//#define MY_RADIO_RFM69

**Comment by henrikekblad** [comment]
Hi @soef! 

Did you read the [details(http://ci.mysensors.org/job/Maintenance/job/MySensorsGitler/802//Issues_detected) from gitler?  You have to amend your PR to have it pass. Instructions available in the link.

**Comment by stintel** [comment]
Fixes #782.
Tested-by Stijn Tintel stijn@linux-ipv6.be

**Comment by henrikekblad** [comment]
Jenkins, build examples please

**Comment by henrikekblad** [comment]
Thanks @soef.

**Comment by saurabhreigns** [comment]
Well i am running a tcp server on 333 port of esp. while using a hotspot running on android device, a client can connect to this tcp server using ESPHOSTNAME:333 but on my router( netgear wsn 110 dual antenna), this doesn’t happen ANYMORE. Earlier , it was flawless. I have tested with some other routers too, almost with every router, this weird behaviour is persistent.
But if i create the wifi hotspot on an android device, connect esp and my other android device running tcp client on it, connection is always established and maintained as long as we keep sending data. 
Please help.
Thanks in advance .

**Pull request merged**
