### PR TITLE
Added default sketch for sensebender samd GW

### PR DESCRIPTION
**Pull request by tbowmo**

### CODE REVIEW

**Comment by fallberg** [comment]
This is an anal comment on indentation.

**Comment by tbowmo** [comment]
Did I miss correct indentation somewhere?

Den man. 1. aug. 2016 23.43 skrev Patrick Fallberg <notifications@github.com

**Comment by tbowmo** [comment]
Ok, now I see it.. Looked ok in atom though. 

I will correct indentation tomorrow

**Comment by tbowmo** [comment]
Indentation should finally be fixed @fallberg, happy now? :)

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by tbowmo** [comment]
Jenkins, build examples please

**Pull request merged**
