### PR TITLE
Add support for RaspberryPi

### PR DESCRIPTION
**Pull request by marceloaqno**

### CODE REVIEW

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Lets try if Jenkins knows slack!
Jenkins, build this please
Jenkins, build examples please

**Comment by fallberg** [comment]
Jenkins, build this please

**Comment by henrikekblad** [comment]
Jenkins, build this please.

**Pull request merged**
