### PR TITLE
Use _msgTmp to build messages

### PR DESCRIPTION
**Pull request by tekka007**
Rational: _msg is used for incoming messages

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
I'm not at computer right now to check, but it could be that the signing backend might need an update as well, as it also sends stuff. Not sure though.

**Comment by tekka007** [comment]
Signing backend uses own instance (_msgSign)

**Comment by fallberg** [comment]
Yes, but I thought of the source of the message to be signed. The one intended to be transmitted by the caller. And also the handshaking. But I think I those already use temp buffer.

**Pull request merged**
