### PR TITLE
Fix missing RF24_NOP refactoring

### PR DESCRIPTION
**Pull request by tekka007**
https://forum.mysensors.org/topic/4803/building-a-raspberry-pi-gateway/103

### CODE REVIEW

**Comment by mfalkvidd** [comment]
great, thanks for fixing @tekka007 
would there be a simple way to have Jenkins detect this type of problem in the future?

**Comment by tekka007** [comment]
yes, but not implemented yet (afaik, ping @fallberg)

**Comment by fallberg** [comment]
What issue is it you want jenkins to detect?
Building linux stuff? That is on the todo list, but I have not been able to raise my workstation from the dead just yet.

**Comment by mfalkvidd** [comment]
I just think that detecting that the code won't even compile should be fairly simple (but still requires some work of course)

**Comment by fallberg** [comment]
Well, anyone is free to submit test sketches to the core repository for this exact purpose. I have done it for signing. So just go ahead if there is a need for something more and perhaps more specific :)

**Comment by fallberg** [comment]
There is no need to update in the ci server. It will look up things to build, so all you need to do is to provide a sketch in the appropriate folder and jenkins will include it when verifying pull requests.

**Pull request merged**
