### PR TITLE
Make WDT_vect weak

### PR DESCRIPTION
**Pull request by Akubi**
Make WDT_vect weak in order to allow local sketch implementation

### CODE REVIEW

**Comment by fallberg** [comment]
This should probably be done for all hw ports for consistency.

**Comment by Akubi** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Only core team members can order Jenkins around. Jenkins, build examples please.

**Comment by Akubi** [comment]
@fallberg 
Ok thank for your help.
I suppose to merge or put to milestone is also only for core team members

**Comment by fallberg** [comment]
Yes. Would you also consider adding the change for the other hw ports as well?

**Comment by Akubi** [comment]
Yes I can do and test but this is for the WatchDog ISR because is implemented as an empty function. 
For which hw ports do you feel this can be interesting to do ?

**Comment by fallberg** [comment]
All ports that implement it. "Sketches" (as in user apps) should be as unified between ports as possible.

**Comment by Akubi** [comment]
Hi. Doing more test, I feel the weak implementation can have side effects.
I propose to suspend this pull request since I done more tests.

**Comment by tekka007** [comment]
@Akubi Can you be a bit more specific, what do you mean by side effects?

**Comment by Akubi** [comment]
Hi, yes sure. I have one sketch where the linker do not load the weak defined ISR.
Of course in that case the result is a WD Reset if you ask a sleep.
I'm actually not sure if it's due to my setup (VisualMicro) or not. 
So I prefer to take more time to test and validate.

**Pull request closed without merging**
