### PR TITLE
Add support for Teensy 3.x

### PR DESCRIPTION
**Pull request by PaulStoffregen**

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Conversation that led to this port.
https://forum.pjrc.com/threads/42601-Add-support-for-Teensy-to-MySensors-library

**Comment by henrikekblad** [comment]
Thanks @PaulStoffregen, 

No one in the MySensors core team have any Teensy (for future verification). Could you send a couple of them to @tekka? 

Also, please sign the CLA.

**Comment by tekka007** [comment]
@PaulStoffregen Your PR needs some attention. Also, for verification purposes and future updates it would be great to get a few Teensy boards.

**Comment by tekka007** [comment]
PR closed due to inactivity, code conflicts and open questions not addressed.

**Comment by PaulStoffregen** [comment]
Sorry, I'm really busy with 2 large projects.  There's no way I can put time into reviewing a legal agreement until at least June.

I can send you a few free Teensy boards for testing.  That's the easy part.

Is this agreement really necessary for such a small patch which really only amounts to a few defines that are just copies of your original code?

**Comment by henrikekblad** [comment]
Thanks for getting back to us @PaulStoffregen. 

We use a standard CLA for all contributions to the MySensors core. It's not uncommon these days for open source projects (I.e. Apache Software Foundation) to avoid future legal problems. Yeah, I know, paranoid. But it's easy to maintain nowadays, so why not.
https://en.wikipedia.org/wiki/Contributor_License_Agreement

Olivier will email his (postal) address to you for the teensy test hardware.

And please rebase the PR when you can squeeze in the time. 

Cheers

**Comment by PaulStoffregen** [comment]
I can send you some Teensy boards for testing.

To sign this, I need to have it reviewed.  Sorry, also a bit paranoid.  And to be honest, a proper review probably will not ever happen.  This just isn't important enough.

Perhaps Luiz Roberto (the user who requested this porting) could redo the work, submit it as a new pull request, and he could sign your agreement?

Sorry, I can not do more here (other than send you some Teensy boards for testing... happy to do that).  Realistically, I probably won't even be able to reply again here.  I just can't put more time into this, even to reply on this pull request.

Please email me directly (paul at pjrc dot com) with your shipping address and I'll arrange to get some hardware sent to you.

**Comment by luizrrocha** [comment]
Hi Henrikeblad,

Since Paul also runs a business around Teensy I can understand why is it much more complicated to sign the CLA.

I agree with his idea of me redoing his work, signing the agreement and allowing an impressive piece of hardware which is Teensy to work with the ever amazing MySensors.

I know for sure that we will be able to count with Paul's support in the future in case any changes outside of my competence to maintain the port arise.

Please let us know.

Regards,

Luiz Roberto Rocha
Rio de Janeiro 
Brazil

**Comment by henrikekblad** [comment]
Sounds good!

**Comment by PaulStoffregen** [comment]
Glad everything worked out well.  :)

**Pull request closed without merging**
