### PR TITLE
Update more usage of hwGetentropy()

### PR DESCRIPTION
**Pull request by d00616**
I have replaced random() with hwGetentropy() calls if available. The keys generated with Linux and SecurityPersonalizer (when supported) now should be more random.

### CODE REVIEW

**Comment by fallberg** [comment]
Could you please also update keywords.txt with the new define(s)?

**Comment by d00616** [comment]
@fallberg Fixed and rebased to actual branch

**Comment by d00616** [comment]
@tekka007 I have added hwGetentropy() to Teensy. After done, I have seen my Board is Teensy 3.2 so i cannot test it. hwGetentropy() is based on your code but I switch of the RNG at the end. Please test it. Thank you.

**Comment by fallberg** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Pull request merged**
