### PR TITLE
MySensors splash screen

### PR DESCRIPTION
**Pull request by tekka007**

### CODE REVIEW

**Comment by fallberg** [comment]
Can we get a demo? The raw data is a bit too "matrix" for me :)

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by fallberg** [comment]
Gitler, check this please

**Comment by fallberg** [comment]
A rebase probably resolves the Gitler complaints.

**Comment by henrikekblad** [comment]
@tekka007, maybe the splash should be printed like normal debug messages on gateway-nodes so it doesn't interfere with the normal command parsing?

**Pull request merged**
