### PR TITLE
Add MY_DEBUGDEVICE to redirect debug output

### PR DESCRIPTION
**Pull request by nelsonov**
As discussed in the forum topic: MY_SERIALDEVICE overrides MY_DEBUG_HWSERIAL

Now includes modifications suggest in previous PR (#1001)

MY_DEBUGDEVICE, if defined, will replace MY_SERIALDEVICE
for the purpose of printing debug messages. This only
applies to debugging.

### CODE REVIEW

**Comment by nelsonov** [comment]
OK, I've tried this several times and obviously I'm lost.  Any help would be appreciated.

**Comment by nelsonov** [comment]
#1004 was the original error.  #1006 was my attempt to fix it, only making things worse.  I have undone those changes but I don't know how to see the errors again from #1004.  That is the problem I need to address.

**Comment by nelsonov** [comment]
There are several commits showing up now.  Perhaps I should squash them all to a single commit.

I am not satisfied that this fixes all cases.  I've noticed that radio debugging (ie MY_DEBUG_VERBOSE_RFM95) disappears completely when MY_DEBUGDEVICE is defined.  I'm trying to track that down now.

**Comment by mfalkvidd** [comment]
@nelsonov the commits are usually squashed before merging to upstream/development, so multiple commits are perfectly fine.

If you want to, you can amend your commit and force-push your branch. Github will then automatically update the PR. I know force push is usually frowned upon, but for PRs it seems to be ok.

**Comment by nelsonov** [comment]
I've noticed that in most cases a module's debugging function is a macro for DEBUG_OUTPUT which itself is a macro for hwDebugPrint:

`#define RF24_DEBUG(x,...)	DEBUG_OUTPUT(x, ##__VA_ARGS__)`

```
MySensors\MyConfig.h:
  1786:  #define DEBUG_OUTPUT(x,...)		hwDebugPrint(x, ##__VA_ARGS__)	//!< debug
```
However, I have noticed three places where the module's debug macro is directly assigned to hwDebugPrint rather than through DEBUG_OUTPUT:
```
MySensors\core\MyOTAFirmwareUpdate.h:
  72:  #define OTA_DEBUG(x,...) hwDebugPrint(x, ##__VA_ARGS__)	//!< debug

MySensors\core\MySigning.cpp:
  28:  #define SIGN_DEBUG(x,...) hwDebugPrint(x, ##__VA_ARGS__)

\MySensors\core\MySigningAtsha204.cpp:
  34:  #define SIGN_DEBUG(x,...) hwDebugPrint(x, ##__VA_ARGS__)
```

Since my changes are to hwDebugPrint itself, my changes are unaffected by this inconsistency, but it did stand out to me as a possible cause for concern.  On the other hand, there may be a good reason for this that I don't know about.

**Comment by tekka007** [comment]
@nelsonov This has been addressed in #1002

**Comment by nelsonov** [comment]
My earlier concerns  about debug information disappearing was actually due to a fried RX pin on one of my boards. This just happened to be the input pin I was using for receiving the redirected debug output. After testing against several other boards, I am satisfied that my changes are working as I expect them to.

**Pull request merged**
