### PR TITLE
RPi: make directly attached RFM69 module work

### PR DESCRIPTION
**Pull request by manuelm**
Apart from fixes (commit 2+3) these commits make a directly attached HopeRF RFM69 module to a Raspberry Pi work.

Since linux is a time-sharing system the Raspberry Pi might loose interrupts or packets because of unfavorable scheduling. However I've been using this since quite some time and unless the system is highly overloaded my system will at least catch the 2nd (out of 3) retries. In general I don't encounter packet loss.

I'm running this on a RPi 1 so I haven't tested multicore behavior. In general the usage of `volatile` in SMP environments and multi-threaded applications (interrupt handler) can cause troubles.

### CODE REVIEW

**Comment by edy** [comment]
+1

this is exactly what i need for my project, too!

**Comment by fallberg** [comment]
@marceloaqno What is your opinion, as the rPi maintainer, on this PR?

**Comment by manuelm** [comment]
I can rebase the commits if you want to pull this. Just waiting for a decision.

**Comment by henrikekblad** [comment]
Hi @manuelm, 

Sorry for a late response. There has been a ongoing work to replace the rmf69 driver for quite some time. The changes you propose in your PR will be incorporated in the release (planned for 2.2.0) along with the new driver.

You can see the ongoing work here:
https://github.com/tekka007/MySensors/commits/RFM69Scalz

Thanks for your effort. I'll be closing this PR now.

**Pull request closed without merging**
